//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.Bussiness.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Bussiness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được trùng.
        /// </summary>
        internal static string ErrorService_Duplicate {
            get {
                return ResourceManager.GetString("ErrorService_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được trùng.
        /// </summary>
        internal static string ErrorService_fixLength {
            get {
                return ResourceManager.GetString("ErrorService_fixLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được quá.
        /// </summary>
        internal static string ErrorService_maxLength {
            get {
                return ResourceManager.GetString("ErrorService_maxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tồn tại.
        /// </summary>
        internal static string ErrorService_notExit {
            get {
                return ResourceManager.GetString("ErrorService_notExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm cửa hàng thất bại.
        /// </summary>
        internal static string ErrorServive_Shop_Insert {
            get {
                return ResourceManager.GetString("ErrorServive_Shop_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cửa hàng không tồn tại.
        /// </summary>
        internal static string ErrorServive_Shop_notExist {
            get {
                return ResourceManager.GetString("ErrorServive_Shop_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID cửa hàng không tồn tại.
        /// </summary>
        internal static string ErrorServive_Shop_ShopId_notExist {
            get {
                return ResourceManager.GetString("ErrorServive_Shop_ShopId_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chỉnh sửa dữ liệu thất bại.
        /// </summary>
        internal static string ErrorServive_Shop_Update {
            get {
                return ResourceManager.GetString("ErrorServive_Shop_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id xã/phường không tồn tại.
        /// </summary>
        internal static string ErrorServive_WardId {
            get {
                return ResourceManager.GetString("ErrorServive_WardId", resourceCulture);
            }
        }
    }
}
